module.exports = {
  apps: [
    {
      name: "clipforge",
      script: "node_modules/.bin/next",
      args: "start",
      cwd: "/var/www/clipforge",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      max_memory_restart: "512M",
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/clipforge/error.log",
      out_file: "/var/log/clipforge/out.log",
      merge_logs: true,
    },
    {
      name: "clipforge-worker",
      script: "npx",
      args: "tsx worker.ts",
      cwd: "/var/www/clipforge",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "256M",
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/clipforge/worker-error.log",
      out_file: "/var/log/clipforge/worker-out.log",
      merge_logs: true,
      restart_delay: 5000,
    },
  ],
};
